### YamlMime:Lifecycle
metadata:
  title: Inteligentná aplikačná brána microsoft 2007
  description: Microsoft Intelligent Application Gateway 2007 sa riadi pevnou politikou životného cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: 6e5cc4784788d27433b7525f6a900cbc1e9f0713
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: sk-SK
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "838439"
name: Inteligentná aplikačná brána microsoft 2007
summary: >
  Microsoft Intelligent Application Gateway 2007 sa riadi pevnou [politikou](/lifecycle/policies/fixed) životného cyklu.



  > [!IMPORTANT]

  > Podpora pre tento produkt sa skončila. Pozri usmernenia o migrácii uvedené nižšie.
products:
- microsoft-servers
policyType: fixed
supportDates:
  start: 06/01/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Service Pack 2
  startDate: 11/27/2008
  endDate: 07/11/2017
- version: Service Pack 1
  startDate: 09/03/2007
  endDate: 01/12/2010
- version: Original Release
  startDate: 06/01/2007
  endDate: 10/14/2008
content: "\n## <a name=\"links\"></a>Odkazy \n* [Plán inteligentnej aplikačnej brány 2007](/archive/blogs/testtesttestbug/important-changes-to-the-forefront-product-line)\n* [Zásady balíka Service Pack](/lifecycle/policies/fixed#service-packs)"
