### YamlMime:Lifecycle
metadata:
  title: Zabezpečenie klienta Microsoft Forefront
  description: Zabezpečenie klienta Microsoft Forefront sa riadi politikou pevných životných cyklov.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: sk-SK
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908900"
name: Zabezpečenie klienta Microsoft Forefront
summary: >+
  Zabezpečenie klienta Microsoft Forefront sa riadi politikou [pevných](/lifecycle/policies/fixed) životných cyklov.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Odkazy \n* [Ochrana koncového bodu v System Center](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Zabezpečenie Forefront Client je zrušené. Podpora končí 14. července, 2015. Aktualizácie definícií antimalvéru a antispyware už nebudú k dispozícii po skončení podpory pre verziu produktu. Vyhodnotí ochranu koncového bodu System Center ako náhradu."
