### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 pre windows desktopy
  description: Microsoft Application Virtualization Hosting 4.6 pre stolné počítače so systémom Windows sa riadi pevnou politikou životného cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: sk-SK
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "838416"
name: Microsoft Application Virtualization Hosting 4.6 pre windows desktopy
summary: >+
  Microsoft Application Virtualization Hosting 4.6 pre stolné počítače so systémom Windows sa riadi pevnou [politikou](/lifecycle/policies/fixed) životného cyklu.


  Toto platí pre nasledujúce vydania: pre windows Desktopy

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Odkazy \n* [Informácie o produkte a migrácii](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Zásady balíka Service Pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Keďže klient App-V 4.6 využíva server App-V 4.5 Server, server App-V 4.5 bude naďalej podporovaný podľa dátumov životného cyklu App-V 4.6, keď sa používa s podporovaným klientom App-V 4.6.\n\n## <a name=\"editions\"></a>Vydania \n* pre pracovné plochy systému Windows"
