### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 sa riadi pevnou politikou životného cyklu.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 sa riadi [pevnou](/lifecycle/policies/fixed) politikou životného cyklu.


  > [!IMPORTANT]
  > Podpora pre tento produkt bola ukončená. Pozri informácie k migrácii uvedené nižšie.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Odkazy 
  * [Informácie k migrácii](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Dodatočné informácie k migrácii](/mem/configmgr/core/migration/planning-for-migration)