### YamlMime:Lifecycle
metadata:
  title: Virtualizácia aplikácií spoločnosti Microsoft 5.1
  description: Microsoft Application Virtualization 5.1 sa riadi pevnou politikou životného cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: 3f0cac2ee013dd73e44fe41d9ba1d07cfcfce2f1
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: sk-SK
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "862466"
name: Virtualizácia aplikácií spoločnosti Microsoft 5.1
summary: >+
  Microsoft Application Virtualization 5.1 sa riadi pevnou [politikou](/lifecycle/policies/fixed) životného cyklu.


  Toto sa týka nasledujúcich vydaní: pre služby vzdialenej pracovnej plochy, pre pracovné plochy systému Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Odkazy \n* [Informácie o produkte](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Vydania \n* pre služby vzdialenej pracovnej plochy\n* pre pracovné plochy systému Windows"
