### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 pre windows desktopy
  description: Microsoft Application Virtualization Hosting 5.1 pre stolné počítače so systémom Windows sa riadi pevnou politikou životného cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: sk-SK
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "862648"
name: Microsoft Application Virtualization Hosting 5.1 pre windows desktopy
summary: >+
  Microsoft Application Virtualization Hosting 5.1 pre stolné počítače so systémom Windows sa riadi pevnou [politikou](/lifecycle/policies/fixed) životného cyklu.


  Toto platí pre nasledujúce vydania: pre windows Desktopy

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Odkazy \n* [Informácie o produkte](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Vydania \n* pre pracovné plochy systému Windows"
