### YamlMime:Lifecycle
metadata:
  title: Zobraziť pôvodný článok v tomto článku sa
  description: Microsoft System Center Configuration Manager 2007 R3 sa riadi pevnou politikou životného cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: cffcc1c2bb51fc5023fe6ad29d62132141ffedb2
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: sk-SK
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "862749"
name: Zobraziť pôvodný článok v tomto článku sa
summary: >
  Microsoft System Center Configuration Manager 2007 R3 sa riadi pevnou [politikou](/lifecycle/policies/fixed) životného cyklu.



  > [!IMPORTANT]

  > Podpora pre tento produkt sa skončila. Pozri usmernenia o migrácii uvedené nižšie.
products:
- msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 12/19/2010
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Odkazy \n* [Usmernenia k migrácii](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Dodatočné usmernenia k migrácii](/mem/configmgr/core/migration/planning-for-migration)"
