### YamlMime:Lifecycle
metadata:
  title: Zabezpečenie klienta Microsoft Forefront
  description: Zabezpečenie klienta Microsoft Forefront sa riadi politikou pevných životných cyklov.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: sk-SK
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924271"
name: Zabezpečenie klienta Microsoft Forefront
summary: >+
  Zabezpečenie klienta Microsoft Forefront sa riadi politikou [pevných](/lifecycle/policies/fixed) životných cyklov.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Odkazy \n* [Ochrana koncového bodu v System Center](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Zabezpečenie Forefront Client je zrušené od štrnásteho júla 2015. Aktualizácie definícií antimalvéru a antispyware už nebudú k dispozícii po skončení podpory pre verziu produktu. Vyhodnotí ochranu koncového bodu System Center ako náhradu."
