### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Microsoft System Center Configuration Manager 2007 R2 sa riadi pevnou politikou životného cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: d74ead7a94de9a66a4f34abab6d8ff9b4496c86479bf1242d36b903855a6e66f
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: sk-SK
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2511293"
name: Microsoft System Center Configuration Manager 2007 R2
summary: "Microsoft System Center Configuration Manager 2007 R2 sa riadi [pevnou](/lifecycle/policies/fixed) politikou životného cyklu. \n\n\n> [!IMPORTANT]\n> Podpora pre tento produkt bola ukončená. Pozri informácie k migrácii uvedené nižšie.\n"
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Odkazy \n* [Informácie k migrácii](/mem/configmgr/core/migration/planning-for-migration)\n* [Dodatočné informácie k migrácii](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
