### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: Microsoft Application Virtualization 5.1 sa riadi pevnou politikou životného cyklu.
  ms.date: 09/10/2020
  keywords: 'for Remote Desktop Services,for Windows Desktops'
name: Microsoft Application Virtualization 5.1
summary: |+
  Microsoft Application Virtualization 5.1 sa riadi [pevnou](/lifecycle/policies/fixed) politikou životného cyklu.

  To platí pre nasledujúce vydania: pre Remote Desktop Services, pre Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Odkazy 
  * [Informácie o produkte](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)


  ## <a name="editions"></a>Vydania 
  * pre služby vzdialenej pracovnej plochy
  * pre Windows Desktops