### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security sa riadi pevnou politikou životného cyklu.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: HT
  ms.contentlocale: sk-SK
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924271"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security sa riadi [pevnou](/lifecycle/policies/fixed) politikou životného cyklu.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Odkazy \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security bola ukončená 14. júla 2015. Aktualizácie definícií antimalvéru a antispyware už nebudú k dispozícii po skončení podpory pre verziu produktu. Zvážte System Center Endpoint Protection ako náhradu."
