### YamlMime:Lifecycle
metadata:
  title: Zobraziť pôvodný článok v tomto článku sa zišiel po anglicky, poejka iadosti o 10 r.R2
  description: Microsoft System Center Configuration Manager 2007 R2 sa riadi pevnú politiku životného cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: 0da71b9a2886e1a7012339ebef9a5fbe64f8811e
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: sk-SK
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "838298"
name: Zobraziť pôvodný článok v tomto článku sa zišiel po anglicky, poejka iadosti o 10 r.R2
summary: >
  Microsoft System Center Configuration Manager 2007 R2 sa riadi pevnú [politiku](/lifecycle/policies/fixed) životného cyklu.



  > [!IMPORTANT]

  > Podpora pre tento produkt sa skončila. Pozri usmernenia o migrácii uvedené nižšie.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Odkazy \n* [Usmernenia k migrácii](/mem/configmgr/core/migration/planning-for-migration)\n* [Dodatočné usmernenia k migrácii](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
