### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization sa riadi pevnou politikou životného cyklu.
  ms.date: 09/10/2020
  keywords: '4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1'
name: SoftGrid Application Virtualization
summary: |
  SoftGrid Application Virtualization sa riadi [pevnou](/lifecycle/policies/fixed) politikou životného cyklu.

  Toto sa vzťahuje na nasledujúce edície: 4.1 for Desktops, 4.2 for Desktops, for Terminal Services 4.1

  > [!IMPORTANT]
  > Podpora bola ukončená. Pozri informácie k migrácii uvedené nižšie.
products:
  - windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
  - version: Original Release
    startDate: 05/25/2007
    endDate: 07/11/2017
content: |

  ## <a name="links"></a>Odkazy 
  * [Informácie k migrácii](https://technet.microsoft.com/en-us/windows/bb899442)


  ## <a name="editions"></a>Vydania 
  * 4.1 for Desktops
  * 4.2 for Desktops
  * for Terminal Services 4.1